apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: "production"
  PORT: "8000"
  DATABASE_URL: "postgres://postgres:postgrespass@postgres-service:5432/messagesdb"
  REDIS_URL: "redis://redis-access:6379"
